### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-dynamodb

on: [push]

env:
  FORCE_COLOR: 1

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: pipx install tox
    - run: tox -e lint

  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - run: pipx install tox
    - run: tox -e $(echo py${{ matrix.python-version }} | tr -d .)
